### ISSUE TITLE
Allow to switch between available color themes

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#108]
Skin config can contain themes section like this:

```YAML
themes:
  - name: green
    resourcekey: "DefaultTheme.Text"
    css: green.min.css
    icon-class: "bg-green"
  - name: a11y
    resourcekey: "A11yTheme.Text"
    css: a11y.min.css
    icon-class: "fas fa-universal-access"
```
