### ISSUE TITLE
Improve custom JS/CSS support

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#141]
General idea is to allow to add additional features w/o including in the skin code directly.

## Option 1
"Plugins" could be generic ASP.NET controls or DNN SkinObjects, dynamically loaded based on configuration. Also need to introduce sample plugin or better implement some skin feature as a plugin.

Possible config sample:

```YAML
plugins:
- name: myPlugin
  src: ~/DesktopModules/MyCompany/MyPlugin/MyPlugin.ascx
- name: myPlugin2
  type: MyCompany.MyPlugin2, MyPlugin2.dll
```

## Option 2

As of its nature, the common plugin serves as a loader of a custom JS, probably passing some server-side variables to it. This makes it more like deprecated DNN widget.

Note that ASP.NET already have script loader, so it could be wise to extend current custom CDNs implementation to support more scenarios. So all you need to add a piece of custom JS is to provide link (external or local) to your JS file. Commonly used page-level variables could be provided via `epsilon` object.
