### ISSUE TITLE
CSS classes for .display-5 and .display-6 headings

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#175]
Bootstrap 4 provides only CSS classes for `.display-1` - `.display-4` headings

**Comment by roman-yagodin** [comment]
```CSS
.display-5 {
    font-size: 2.5rem;
    font-weight: 300;
    line-height: 1.2;
}

.display-6 {
    font-size: 1.5rem;
    font-weight: 300;
    line-height: 1.2;
}
```
