### ISSUE TITLE
Increase DNN QuickSettings form padding

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#212]
This could make nasty "close on unhover" effect appear less frequently.

**Comment by roman-yagodin** [comment]
```CSS
.qsContainer {
  padding:0.5rem
}
```
