### ISSUE TITLE
Side banners are still visible in mobile browsers

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#237]
Quickfix: add the following code to the `portal.css`

```CSS
.skin-sidebanner-panes {
    display: none;
}
@media only screen and (min-width: 1510px) {
	.skin-sidebanner-panes {
		display: block;
	}
}
```
