### ISSUE TITLE
New Year theme

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#91]
- Reuse "consulting" skin theme
- Snowdrift background
- Some tweaks for menu and round logo
- Enable jQuery-Snowfall for header from [here](https://github.com/roman-yagodin/R7.Dnn.JavaScriptLibraries)
- Provide config option to it

**Comment by roman-yagodin** [comment]
```CSS
.skin-primary-navbar-main {
    background-image: url('http://www.volgau.com/Portals/0/Images/new_year_header.png');
}

img#dnn_dnnLOGO_imgLogo {
  border-radius: 50px;
}

.skin-secondary-menu ul.megamenu li.level0 > a {
  border-radius:4px;
}
```
